#!/usr/bin/env bash
# A Bash script that configures a new ubuntu machine
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER:$USER" /var/www/html/index.nginx-debian.html
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
