#!/usr/bin/env bash
# Configure an Ubuntu machine
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/ugwujustine/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
