#!/usr/bin/env bash
# setting up 404 error code page

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://github.com/ugwujustine permanent;" /etc/nginx/sites-enable/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "/listen 80 default_server/a error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
