#!/usr/bin/env bash
# Sever configuration
sudo apt update
sudo apt install curl -y
sudo apt install nginx -y
sudo service start nginx
sudo service enable nginx
rm /etc/nginx/site-available/*
rm /etc/nginx/site-enabled/*~
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/site-enabled/default
sudo service nginx restart
