#!/usr/bin/env bash
# A Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid
# and terminates itself when receiving a SIGQUIT or SIGTERM signal

# Function to handle SIGTERM and SIGQUIT
terminate() {
	echo "I hate the kill command"
	rm -f "/var/run/myscript.pid"
	exit 0
}

# function to handle SIGINT
interrupt() {
	echo "Y U no love me?!"
}

# register signal
trap terminate 15 3
trap interrupt 2

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done
