#!/usr/bin/env bash
# A bash script that displays best school 10x 
# but for the 9th iteration, displays hi

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best Schol"
	fi
	((counter++))
done
