#!/usr/bin/env bash
# A bash script that displays the content of the current direcory

for file in *; do
	if [ -f "$file" ]; then
		name_after_dash=$(echo "$file" | cut -d '_' -f 2-)
		echo " $name_after_dash"
	fi
done
