#!/usr/bin/env bash
# A bash script that gives you information about the school file

file="school"

if [ -e "$file" ]; then
	echo "shool file exists"

	if [ -s "$file" ]; then
		echo "school file is not empty"

		if [ -f "$file" ]; then
			echo "school is a regular file"
		fi
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
