#!/usr/bin/env bash
# A bash scrip that configures an ubuntu server
if [ "$(id -u)" != "0" ]; then
	echo "Please run this script as root."
	exit 1
fi

sed -i "s/127.*.*.* localhost/127.0.0.2 localhost/" /etc/hosts

if grep -Fxq "facebook.com" /etc/hosts
then
	sed -i "s/*.*.*.* facebook.com/8.8.8.8 facebook.com/" /etc/hosts
else
	sed -i '1s/^/8.8.8.8 facebook\n/' /etc/hosts
fi
