#!/usr/bin/env bash
# A bash scrip that configures an ubuntu server
if [ "$(id -u)" != "0" ]; then
	echo "Please run this script as root."
	exit 1
fi

echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8 facebook.com" >> /etc/hosts

echo "Configuration complete: localhost now resolves"
