#!/usr/bin/env bash
# A Bash script that configures the container to run as nginx user

sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/site-available/default

chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo service nginx restart
